import { useState } from 'react';
import { PlusIcon } from '@heroicons/react/24/outline';
import type { QuickAddProps } from '@/types/memory';

export const QuickAdd: React.FC<QuickAddProps> = ({ onAdd }) => {
  const [content, setContent] = useState('');
  const [isExpanded, setIsExpanded] = useState(false);

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    if (!content.trim()) return;

    onAdd({
      content: content.trim(),
      ai_tags: [], // Will be generated by AI
      category: 'Uncategorized', // Will be categorized by AI
      isPinned: false,
    });

    setContent('');
    setIsExpanded(false);
  };

  return (
    <div className="bg-white dark:bg-gray-800 rounded-lg shadow-md p-4 mb-6">
      <form onSubmit={handleSubmit}>
        <div className="flex flex-col space-y-4">
          <div className="flex items-center space-x-4">
            <textarea
              value={content}
              onChange={(e) => setContent(e.target.value)}
              onFocus={() => setIsExpanded(true)}
              placeholder="What's on your mind?"
              className="flex-1 min-h-[40px] p-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:ring-2 focus:ring-blue-500 focus:border-transparent dark:bg-gray-700 dark:text-white resize-none"
              rows={isExpanded ? 3 : 1}
            />
          </div>

          {isExpanded && (
            <div className="flex justify-end">
              <button
                type="submit"
                disabled={!content.trim()}
                className="px-4 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 disabled:opacity-50 disabled:cursor-not-allowed flex items-center space-x-2"
              >
                <PlusIcon className="h-5 w-5" />
                <span>Add Memory</span>
              </button>
            </div>
          )}
        </div>
      </form>
    </div>
  );
}; 